### ISSUE TITLE
Workarounds for Shuosin 

### ISSUE THREAD

**Issue by tampe125** [akeeba/kickstart#16]
For what I know, Shuosin is now obsolete and no longer maintained (last changelog entry dates back to 2016).
Given that this is an internal tool, should we really need to detect and work around Shuosin, like we're doing in `minibuild.php`?

Seems dead code to me.
Paging @nikosdion for confirm

**Comment by nikosdion** [comment]
Leave that code in place. Old versions of PHP are still a thing :( It will be another 2-3 years before the majority of these old PHP versions are removed or we stop supporting them. Basically: once we drop PHP 7.2 support we can remove Suhosin checks.
