### ISSUE TITLE
jpa files

### ISSUE THREAD

**Issue by ppetree** [akeeba/kickstart#24]
What is the easiest way to get one file from a backup?

**Comment by nikosdion** [comment]
Command line: `/path/to/php kickstart.php archive.jpa --extract=relative/path/of/file/in/archive`

Web: select the archive and scroll all the way down the page. Find the Files To Extract option. Enter the name of the file in the format `relative/path/of/file/in/archive`. The click on Start.

**Comment by ppetree** [comment]
Awesome. Thanks.
