### ISSUE TITLE
Improve error message when one or more backup parts are missing

### ISSUE THREAD

**Issue by tampe125** [akeeba/kickstart#30]
Currently, if one or more parts of the backup archive are missing, we display a generic "This is not a JPA archive" error message.  
Technically this is true, but it's not very helpful for the customer.  

We should display a better message, asking the customer if they truly uploaded all the parts.

**Comment by nikosdion** [comment]
So, the problems comes down to which error message we display. For ZIP files we display ERR_CORRUPT_ARCHIVE (“The archive file is corrupt, truncated or archive parts are missing”). For JPA and JPS we use ERR_NOT_A_JPA_FILE (“The file is not a JPA archive”) and ERR_NOT_A_JPS_FILE (“The file is not a JPA archive”).

When we read the first part and there is no signature in the first 128Kb I will now be printing the ERR_CORRUPT_ARCHIVE and change it to have clearer instructions on what to do.
