### ISSUE TITLE
How to exclude a folder when extracting a JPA backup

### ISSUE THREAD

**Issue by wdammak** [akeeba/kickstart#8]
Hello Best Team,
I have a file that causes me an error while extracting JPA, how to exclude a folder when extracting a JPA backup?

**Comment by nikosdion** [comment]
You cannot exclude a folder. You can only tell it which files / folder to extract. However you don't need this in your case. Just click "Ignore most errors" to tell Kickstart to ignore Windows filesystem errors.

**Comment by wdammak** [comment]
I don't understand why it isn't possible? it's technically impossible or a missing feature?
At the time of extracting the file, It isn't possible to check if the file in a list to exclude?
Thx

**Comment by nikosdion** [comment]
This is a feature that is neither implemented, nor am I interested in implementing. Feel free to modify the code yourself. That's why Kickstart is Free and Open Source Software :)
